export const dummy = [
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    displayName: "asdf",
    content: "testing chat with a really really long message about nothing",
    type: "chat",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  { displayName: "asdf", content: "testing chat", type: "chat" },
  {
    content: "testing notification",
    type: "notification",
  },
  { displayName: "asdf", content: "testing chat", type: "chat" },
];
